# Default FujiNet disk for Workbench 3.2.  It is deliberately FFS/DD.
label: FNDEFAULT
output: build/FujiNet-Default-WB32.adf

files:
  - build/amiga-artifacts/wb32/NIO/config-nio
  - build/amiga-artifacts/wb32/NIO/config-nio.info
  - build/amiga-artifacts/wb32/NIO/fapp
  - build/amiga-artifacts/wb32/NIO/fboot
  - build/amiga-artifacts/wb32/NIO/fdrive
  - build/amiga-artifacts/wb32/NIO/fhost
  - build/amiga-artifacts/wb32/NIO/fin
  - build/amiga-artifacts/wb32/NIO/fls
  - build/amiga-artifacts/wb32/NIO/fmount
  - build/amiga-artifacts/wb32/NIO/fmountrestore
  - build/amiga-artifacts/wb32/NIO/fout
  - build/amiga-artifacts/wb32/NIO/fumount
